name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install musl-gcc5
      run: |
        curl https://musl.cc/x86_64-w64-mingw32-cross.tgz > /tmp/x86_64-w64-mingw32-cross.tgz
        tar zxf /tmp/x86_64-w64-mingw32-cross.tgz -C /tmp
    - name: Build
      run:  |
        export PATH=$PATH:/tmp/x86_64-w64-mingw32-cross/bin
        CGO_ENABLED=1 go build -trimpath -ldflags "-w -s" -buildmode=c-shared -o ./linux/libgml.so
        CGO_ENABLED=1 GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ go build -trimpath -ldflags "-w -s" -buildmode=c-shared -o ./windows/libgml.dll
    - name: Test
      run: go test -v ./...
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
       name: linux
       path: ./linux/*
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
       name: windows
       path: ./windows/*
   
     
